const siswa = [
  { nama: "ACHMAD RICKY DIANTORO", hobi: "Kegiatan keagamaan", deskripsi: "Aktif dalam kegiatan rohani, bijak dalam bersikap, dan menjadi teladan di kelas.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "AIS SAHWA ALIYA", hobi: "Melukis dan menggambar", deskripsi: "Memiliki imajinasi tinggi, karya seninya sering dipajang di sekolah.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "AMEZZA ARIO BAGAS SAPUTRA", hobi: "Riding dan dunia otomotif", deskripsi: "Suka modifikasi motor dan sering ikut komunitas motor lokal.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "ANANDA EVRILIA INDAH AZZAHROH", hobi: "Pramuka dan paskibra", deskripsi: "Berprestasi akademik dan aktif organisasi, inspirasi bagi teman-temannya.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "ANDHIKA PUTRA TRIWARDANI", hobi: "Wirausaha dan jualan online", deskripsi: "Pandai membaca peluang usaha dan sudah punya brand sendiri sejak SMA.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "ANGGI ANGGRAINI AYU WULANDARI", hobi: "Membaca novel dan berkebun", deskripsi: "Penyuka ketenangan, suka berbagi cerita dari buku yang dibacanya.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "ARIS WAHYUDI", hobi: "Olahraga basket dan lari", deskripsi: "Atletik dan energik, sering mewakili sekolah di ajang olahraga.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "AULIA BUNGA MELINA ANGGRAENI", hobi: "Fotografi dan jurnal", deskripsi: "Punya kepekaan tinggi menangkap momen melalui kamera dan tulisan.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "AULIA PUTRI KUSUMA WARDHANI", hobi: "Paskibra dan OSIS", deskripsi: "Tegas, disiplin, dan menjadi penggerak kegiatan sekolah.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "DIAH ANJAR CAHYANINGRUM", hobi: "Crafting dan memasak", deskripsi: "Kreatif di dapur dan senang membuat kerajinan tangan unik.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "FARIS IRMA DWI PRASETYA", hobi: "Meme dan teknologi", deskripsi: "MSelalu update tren internet, sering jadi pusat perhatian karena humornya.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "GALANG ARYA PRATAMA", hobi: "Komunitas motor dan touring", deskripsi: "Suka petualangan dan menjelajah tempat baru bersama komunitasnya.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "GRENNIEL GONI FIRMANSYAH", hobi: "Sepak bola dan futsal", deskripsi: "Pemain andalan tim sekolah dan sangat kompetitif di lapangan.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "JACINDA IGNACIA EKA REDIANA", hobi: "Pramuka dan organisasi", deskripsi: "Tangguh dan cekatan, selalu siap jadi pemimpin kegiatan outdoor.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "JULIA", hobi: "Pramuka dan kegiatan sosial", deskripsi: "Peduli sesama dan aktif mengajak teman-teman terlibat aksi sosial.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "LINTANG GALIH ARDINANSYAH", hobi: "Silat dan bela diri", deskripsi: "Disiplin dan fokus, sering juara lomba silat tingkat kota.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "M DAFFA PUTRA ADAM PRATAMA", hobi: "Desain grafis dan menulis blog", deskripsi: "Mahir menggunakan aplikasi desain dan punya blog inspiratif", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "MEISYA NUR AZIZAH ARLAIKA", hobi: "Bahasa Inggris dan sastra", deskripsi: "Suka membaca karya klasik dan pandai berbahasa asing.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "MOHANGGA ARSY SYAHQOLY", hobi: "Renang dan olahraga outdoor", deskripsi: "Suka tantangan fisik dan aktif ikut lomba-lomba olahraga.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "MOHAMMAD ADITYA PRATAMA", hobi: "Gaming dan e-sport", deskripsi: "Strategis dan fokus, bercita-cita menjadi atlet e-sport profesional.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "MOHAMMAD FARDAN SAPUTRA", hobi: "Futsal dan bola voli", deskripsi: "Sangat aktif di kegiatan olahraga sekolah dan dikenal sportif.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "MUHAMMAD AULIYAN MUSTOFA", hobi: "Memasak dan eksperimen resep", deskripsi: "Pintar di dapur dan sering jadi andalan saat ada lomba masak.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "MUHROMIN", hobi: "Ngoding dan robotik", deskripsi: "Tekun belajar pemrograman dan sering ikut lomba inovasi teknologi.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "NINA AULIA NUR OKTAVIANI", hobi: "Origami dan menulis puisi", deskripsi: "Punya sisi seni dan imajinasi yang kuat, puisinya sering jadi inspirasi.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "NOVITA AMBARWATI", hobi: "Membuat jurnal dan kaligrafi", deskripsi: "Punya tulisan tangan indah dan kreatif dalam menghias jurnal.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "NUR MUHAMAD FAJAR ARYA PRATAMA", hobi: "Karate", deskripsi: "Bermental kuat dan punya disiplin tinggi, juara karate antar sekolah.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "RARA AULIA NURSAFA", hobi: "Bernyanyi dan teater", deskripsi: "Punya suara merdu dan ekspresif saat tampil di panggung.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "REGITA FARA NAILATUL FITRIA", hobi: "Pramuka dan debat", deskripsi: "Pemimpin regu dan pembicara yang percaya diri saat debat.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "RINI AGUSTINA", hobi: "Drama Korea dan skincare", deskripsi: "Suka dunia kecantikan dan hobi berbagi tips perawatan wajah.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "SITI DEWI MASITHOH", hobi: "Menulis cerpen dan membaca", deskripsi: "Suka menyusun cerita dan sering jadi juara lomba literasi.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "TASYA AMALIYA PUTRI", hobi: "Melukis cat air", deskripsi: "Karyanya penuh warna dan emosi, suka ikut pameran seni.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "VEGA SURYA SAPUTRA", hobi: "Silat dan bela diri", deskripsi: "Selalu tampil percaya diri, gigih berlatih untuk kompetisi.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "VINA PUTRI ANDRIANI PRATAMA", hobi: "Travelling dan vlog", deskripsi: "Suka eksplorasi tempat baru dan berbagi lewat konten kreatif.", color: "bg-green-100", icon: "text-green-500" },
  { nama: "Wiradinata Mas Sembada Yuswanto", hobi: "Futsal (kiper utama)", deskripsi: "Handal menjaga gawang dan sering jadi penentu kemenangan tim.", color: "bg-indigo-100", icon: "text-indigo-500" },
  { nama: "YOHAN BAGAS ADI SAPUTRA", hobi: "Bisnis online dan startup", deskripsi: "Berjiwa pengusaha dan aktif membangun brand sejak dini.", color: "bg-blue-100", icon: "text-blue-500" },
  { nama: "Zulkifla Helfina Prasetyo", hobi: "Game simulasi dan membaca", deskripsi: "Punya ketertarikan pada simulasi bisnis dan strategi hidup.", color: "bg-green-100", icon: "text-green-500" },
];
